---
headscale_version: "0.29.1"
headscale_arch: "amd64"

headscale_listen_addr: "127.0.0.1:8080"

headscale_db_path: "/var/lib/headscale/db.sqlite"
headscale_noise_private_key_path: "/var/lib/headscale/noise_private.key"
