---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/ansible/radarr/config:/config
      # - /path/to/movies:/movies #optional
      # - /path/to/download-client-downloads:/downloads #optional
    restart: unless-stopped
    network_mode: host
