- name: Add Docker GPG Key
  ansible.builtin.rpm_key:
    state: present
    key: https://download.docker.com/linux/fedora/gpg

- name: Add Docker Repository
  ansible.builtin.yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/fedora/gpg
    enabled: true

- name: Update dnf and install Docker
  ansible.builtin.dnf5:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: present
    update_cache: true
