---
- name: Common
  hosts: control_server
  become: true
  roles:
    - common

- name: Control Server
  hosts: control_server
  become: true

  pre_tasks:
    - name: Check if Tailscale is installed
      ansible.builtin.shell: |
        tailscale version
      register: tailscale_check
      ignore_errors: true
      changed_when: false

    - name: Set fact for Tailscale presence
      ansible.builtin.set_fact:
        tailscale_installed: "{{ tailscale_check.rc == 0 }}"

  roles:
    - role: artis3n.tailscale.machine
      tags: [needs-secrets]
      vars:
        tailscale_authkey: "{{ lookup('community.general.bitwarden', 'tailscale_auth_key', field='notes')[0] }}"
        tailscale_args: "--login-server=http://127.0.0.1:8080 --accept-dns"
      when: not tailscale_installed
    - headscale
    - role: headplane
      tags: [needs-secrets]
    - caddy
    - fail2ban
